# Generated by Django 5.1.6 on 2025-02-26 09:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTable',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('discription', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='beach.jpg', null=True, upload_to='')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
