# Generated by Django 5.1.6 on 2025-02-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtable',
            name='image2',
            field=models.ImageField(blank=True, default='beach.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogtable',
            name='image3',
            field=models.ImageField(blank=True, default='beach.jpg', null=True, upload_to=''),
        ),
    ]
