# Generated by Django 5.1.6 on 2025-03-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtable',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='blogtable',
            name='image3',
        ),
    ]
