# Generated by Django 5.1.6 on 2025-03-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogtable_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtable',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
